/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import DatabaseLayer.DatabaseConnection;

import javax.swing.*;
import java.sql.*;
import java.awt.Event.*;

import Model.InvalidInputException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.PreparedStatement;

/**
 *
 * @author bsc2017
 */
public class GenerateAdmissionCard extends javax.swing.JFrame {

    /**
     * Creates new form GenerateAdmissionCard
     */
    public GenerateAdmissionCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtyear = new javax.swing.JTextField();
        txtSemester = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtStudentId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSubjects = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generating Admission Card");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Student ID :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 70, 140, 30);
        jPanel1.add(txtStudentID);
        txtStudentID.setBounds(190, 70, 290, 30);

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 120, 90, 25);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 480, 90, 35);
        jPanel1.add(txtyear);
        txtyear.setBounds(140, 250, 260, 30);
        jPanel1.add(txtSemester);
        txtSemester.setBounds(140, 290, 260, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Year");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 250, 60, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Semester");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 290, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 210, 50, 30);
        jPanel1.add(txtName);
        txtName.setBounds(140, 210, 260, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Student ID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 170, 70, 30);
        jPanel1.add(TxtStudentId);
        TxtStudentId.setBounds(140, 170, 260, 30);

        txtSubjects.setColumns(20);
        txtSubjects.setRows(5);
        jScrollPane1.setViewportView(txtSubjects);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 330, 260, 130);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Subjects");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 330, 90, 30);

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(400, 490, 70, 25);

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(40, 490, 70, 25);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel7.setText("Generate Admission Card");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(160, 10, 260, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/620 x 650.JPG"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 530, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        function f = new function();
        ResultSet rs = null;
        String sd = "StudentID";
        String nm = "StudentName";
        String yr = "year";
        String Sm = "Semester";
        String su = "SubjectName";

        rs = f.find(txtStudentID.getText());
        try {

            if (rs.next()) {

                TxtStudentId.setText(rs.getString("StudentID"));
                txtName.setText(rs.getString("StudentName"));
                txtyear.setText(rs.getString("year"));
                txtSemester.setText(rs.getString("Semester"));
                txtSubjects.setText(rs.getString("SubjectName"));

            } else {
                JOptionPane.showMessageDialog(null, "Invalid StudentID");
            }

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage());
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            FileWriter fw = new FileWriter("C:\\Users\\bsc2017\\Desktop\\"+TxtStudentId.getText()+".txt");
            BufferedWriter bw = new BufferedWriter(fw);

            TxtStudentId.write(bw);
            bw.newLine();
            txtName.write(bw);
                bw.newLine();
            txtyear.write(bw);
                bw.newLine();
            txtSemester.write(bw);
                bw.newLine();
            txtSubjects.write(bw);
            

            bw.close();
            
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txtStudentID.setText(" ");
        TxtStudentId.setText(" ");
        txtName.setText(" ");
        txtyear.setText(" ");
        txtSemester.setText(" ");
        txtSubjects.setText(" ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    
    public class function {

        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement ps = null;

        public ResultSet find(String s) {
            try {
                conn = DriverManager.getConnection("jdbc:sqlserver://SQLSERVERSLIITC:1433;databaseName=OOP2018;user=OOP2018;password=OOP");

                ps = conn.prepareStatement("select a.StudentID,a.StudentName,b.year,b.Semester,b.SubjectName from IT17255516StudentTable a,IT17255516SubjectTable b,IT17255516EnrollingTable c  where a.StudentID=c.StudentID and b.SubjectCode=c.SubjectCode and a.StudentID=? ");
                ps.setString(1, s);
                rs = ps.executeQuery();
            } catch (Exception ex) {

                JOptionPane.showMessageDialog(null, ex.getMessage());

            }
            return rs;
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerateAdmissionCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerateAdmissionCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerateAdmissionCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerateAdmissionCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerateAdmissionCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtStudentId;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSemester;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextArea txtSubjects;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
