/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.util.Properties;
import javax.activation.DataHandler;

import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class SendingNotifications extends javax.swing.JFrame {

    /**
     * Creates new form SendingNotifications
     */
    public SendingNotifications() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        To = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        txtField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        txtpath = new javax.swing.JTextField();
        txtAtachmentName = new javax.swing.JLabel();
        txtAtachmentNamee = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Send Notifications");

        jPanel1.setLayout(null);

        To.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        To.setText("To");
        jPanel1.add(To);
        To.setBounds(40, 80, 94, 30);
        jPanel1.add(txtTo);
        txtTo.setBounds(120, 80, 290, 30);

        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });
        jPanel1.add(txtField);
        txtField.setBounds(40, 190, 370, 130);

        jButton1.setText("Send Mail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 520, 90, 35);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 570, 70, 25);

        jButton3.setText("Attachments");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(40, 330, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Subject");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 120, 90, 30);
        jPanel1.add(txtSubject);
        txtSubject.setBounds(120, 120, 290, 30);
        jPanel1.add(txtpath);
        txtpath.setBounds(40, 400, 370, 30);
        jPanel1.add(txtAtachmentName);
        txtAtachmentName.setBounds(519, 353, 80, 27);
        jPanel1.add(txtAtachmentNamee);
        txtAtachmentNamee.setBounds(40, 470, 370, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        jLabel3.setText("Send Notifications");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 10, 170, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Body");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 70, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Attachments path");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 370, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Attachment name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 440, 140, 30);

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(340, 570, 70, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FrontEnd/620 x 650.JPG"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 460, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        attachementpath = f.getAbsolutePath();
        
        txtpath.setText(attachementpath);
        

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String To_Recieve = txtTo.getText();
        String Subject = txtSubject.getText();
        String Text_content = txtField.getText();
        
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.port", "587");
        
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                    
                    @Override
                    protected PasswordAuthentication getPasswordAuthentication() {
                        
                        return new PasswordAuthentication("supun.thiwanka@gmail.com", "thiwanka63070");
                        
                    }
                    
                }
        );
        
        try {
            
            Message message = new MimeMessage(session);
            
            message.setFrom(new InternetAddress("supun.thiwanka@gmail.com"));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(To_Recieve));
            message.setSubject(Subject);
            message.setText(Text_content);
            
            MimeBodyPart messagebodypart = new MimeBodyPart();
            
            messagebodypart.setText(Text_content);
            
            Multipart multipart = new MimeMultipart();
            
            multipart.addBodyPart(messagebodypart);
            
            messagebodypart = new MimeBodyPart();
            javax.activation.DataSource source = new FileDataSource(attachementpath);
            
            messagebodypart.setDataHandler(new DataHandler(source));
            
            messagebodypart.setFileName(txtAtachmentNamee.getText());
            
            multipart.addBodyPart(messagebodypart);
            Transport.send(message);
            message.setContent(multipart);
            
            JOptionPane.showMessageDialog(null, "message Sent");
            
        } catch (Exception ex) {
            
            JOptionPane.showMessageDialog(null, ex);
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtTo.setText(" ");
        txtSubject.setText(" ");
        txtField.setText(" ");
        txtAtachmentNamee.setText(" ");
        txtpath.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Home h = new Home();
        h.setVisible(true);
        close();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    public void close() {

        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendingNotifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendingNotifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendingNotifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendingNotifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendingNotifications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel To;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtAtachmentName;
    private javax.swing.JTextField txtAtachmentNamee;
    private javax.swing.JTextField txtField;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTo;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables

    private File file;
    String date1, date2, possibleaction, File_path, filename1;
    
    String attachementpath;
    
}
